name: Sync OAS to ReadMe
on:
  push:
    branches:
      - main
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: readmeio/github-readme-sync@v2
        with:
          readme-oas-key: ${{ secrets.README_OAS_KEY_2}}
          oas-file-path: '../project2.json'
          api-version: 'v1.0.3'